In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [5]:
a = np.random.randint(1,19,10)
a

array([ 8, 15, 17,  2, 16, 12, 14,  3, 10,  9])

In [6]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
a = [5]
a*10

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [9]:
a = np.array([10,20,30,11,22,30,40,50,30])
a

array([10, 20, 30, 11, 22, 30, 40, 50, 30])

In [10]:
a = a.reshape(3,3)
a

array([[10, 20, 30],
       [11, 22, 30],
       [40, 50, 30]])

In [11]:
a = np.random.rand(3,3)
a

array([[0.88531959, 0.87477   , 0.32335729],
       [0.65245154, 0.16144741, 0.46928792],
       [0.72819428, 0.78323917, 0.66615036]])

In [15]:
a = np.array([3,4,5,6])
a

array([3, 4, 5, 6])

In [16]:
a = a.reshape(2,2)
a

array([[3, 4],
       [5, 6]])

In [17]:
np.hstack((a))

array([3, 4, 5, 6])

In [18]:
np.vstack((a))

array([[3, 4],
       [5, 6]])