In [1]:
# Ordinal Encoder ====>> Multi - Categrical data encode 

In [9]:
import numpy as np 
import pandas as pd 

In [10]:
df = pd.read_csv("C:\\Users\\saurabh\\Desktop\\Newdat\\covid_toy.csv")

In [11]:
df.head(2) 

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [12]:
df = df.dropna() 

In [13]:
from sklearn.preprocessing import OrdinalEncoder 

In [14]:
df = df.drop(columns = ['age' , 'fever'])

In [15]:
df

gender   cough       city has_covid
0     Male    Mild    Kolkata        No
1     Male    Mild      Delhi       Yes
2     Male    Mild      Delhi        No
3   Female    Mild    Kolkata        No
4   Female    Mild     Mumbai        No
..     ...     ...        ...       ...
95  Female    Mild  Bangalore        No
96  Female  Strong    Kolkata       Yes
97  Female    Mild  Bangalore        No
98  Female  Strong     Mumbai        No
99  Female  Strong    Kolkata       Yes

[90 rows x 4 columns]

In [16]:
df['gender'].value_counts()

Female    54
Male      36
Name: gender, dtype: int64

In [17]:
df['cough'].value_counts()

Mild      57
Strong    33
Name: cough, dtype: int64

In [18]:
df['city'].value_counts()

Kolkata      29
Bangalore    28
Delhi        20
Mumbai       13
Name: city, dtype: int64

In [19]:
df['has_covid'].value_counts()

No     52
Yes    38
Name: has_covid, dtype: int64

In [21]:
oe = OrdinalEncoder(categories=[['Male' , 'Female'],['Mild' , 'Strong'] , 
                                ['Kolkata' , 'Bangalore' , 'Delhi' , 'Mumbai'], ['No' , 'Yes']])

In [22]:
df.head(3)

gender cough     city has_covid
0   Male  Mild  Kolkata        No
1   Male  Mild    Delhi       Yes
2   Male  Mild    Delhi        No

In [23]:
oe

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [24]:
oe.fit(df) 

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [25]:
df_new = oe.transform(df) 

In [27]:
df_new = pd.DataFrame(df_new , columns = ['gender' , 'cough' , 'city' , 'has_covid'])

In [28]:
df_new

gender  cough  city  has_covid
0      0.0    0.0   0.0        0.0
1      0.0    0.0   2.0        1.0
2      0.0    0.0   2.0        0.0
3      1.0    0.0   0.0        0.0
4      1.0    0.0   3.0        0.0
..     ...    ...   ...        ...
85     1.0    0.0   1.0        0.0
86     1.0    1.0   0.0        1.0
87     1.0    0.0   1.0        0.0
88     1.0    1.0   3.0        0.0
89     1.0    1.0   0.0        1.0

[90 rows x 4 columns]

In [29]:
from sklearn.preprocessing import StandardScaler 

In [30]:
sc = StandardScaler() 

In [32]:
df_sc = sc.fit_transform(df_new)

In [33]:
df_new_sc= pd.DataFrame(df_sc , columns = df_new.columns) 

In [34]:
np.round(df_new_sc.describe() , 2)

gender  cough   city  has_covid
count   90.00  90.00  90.00      90.00
mean     0.00   0.00  -0.00      -0.00
std      1.01   1.01   1.01       1.01
min     -1.22  -0.76  -1.14      -0.85
25%     -1.22  -0.76  -1.14      -0.85
50%      0.82  -0.76  -0.18      -0.85
75%      0.82   1.31   0.78       1.17
max      0.82   1.31   1.74       1.17

# OneHotEncoder

In [51]:
df = pd.read_csv("C:\\Users\\saurabh\\Desktop\\Newdat\\covid_toy.csv")

In [52]:
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [53]:
df = df.dropna() 

In [54]:
df = df.drop(columns = ['age' , 'fever'])

In [61]:
df

gender   cough       city has_covid
0     Male    Mild    Kolkata        No
1     Male    Mild      Delhi       Yes
2     Male    Mild      Delhi        No
3   Female    Mild    Kolkata        No
4   Female    Mild     Mumbai        No
..     ...     ...        ...       ...
95  Female    Mild  Bangalore        No
96  Female  Strong    Kolkata       Yes
97  Female    Mild  Bangalore        No
98  Female  Strong     Mumbai        No
99  Female  Strong    Kolkata       Yes

[90 rows x 4 columns]

In [55]:
# gender ==> Male , Female 

In [56]:
from sklearn.preprocessing import OneHotEncoder 

In [57]:
ohe = OneHotEncoder(drop = 'first' , sparse = False , dtype = np.int32) 

In [58]:
df_new = ohe.fit_transform(df[['gender' , 'cough' , 'city' , 'has_covid']]) 

In [59]:
df_new

array([[1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
 

In [60]:
df.shape

(90, 4)

In [62]:
df_new.shape

(90, 6)

In [67]:
df = pd.read_csv("C:\\Users\\saurabh\\Desktop\\Newdat\\tips.csv")

In [68]:
df.head(3) 

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [69]:
df = df.dropna()

In [70]:
df = df.drop(columns = ['total_bill' , 'tip' , 'size'])
df

sex smoker   day    time
0    Female     No   Sun  Dinner
1      Male     No   Sun  Dinner
2      Male     No   Sun  Dinner
3      Male     No   Sun  Dinner
4    Female     No   Sun  Dinner
..      ...    ...   ...     ...
239    Male     No   Sat  Dinner
240  Female    Yes   Sat  Dinner
241    Male    Yes   Sat  Dinner
242    Male     No   Sat  Dinner
243  Female     No  Thur  Dinner

[244 rows x 4 columns]

In [71]:
df['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [72]:
df['time'].value_counts() 

Dinner    176
Lunch      68
Name: time, dtype: int64

In [73]:
oe = OrdinalEncoder(categories = [['Female' , 'Male'] , ['No' , 'Yes'] ,
                                  ['Sat','Sun' ,'Thur' , 'Fri'],['Dinner' , 'Lunch']])

In [74]:
oe

OrdinalEncoder(categories=[['Female', 'Male'], ['No', 'Yes'],
                           ['Sat', 'Sun', 'Thur', 'Fri'], ['Dinner', 'Lunch']])

In [75]:
oe.fit(df) 

OrdinalEncoder(categories=[['Female', 'Male'], ['No', 'Yes'],
                           ['Sat', 'Sun', 'Thur', 'Fri'], ['Dinner', 'Lunch']])

In [77]:
df_ordinal = oe.transform(df) 

In [78]:
df_ordinal

array([[0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],


In [79]:
ohe = OneHotEncoder(drop = 'first' , sparse = False , dtype = np.int32) 

In [81]:
df_new = ohe.fit_transform(df[['sex' , 'smoker' , 'day' , 'time']]) 

In [83]:
df_new

array([[0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       ...,
       [1, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0]])