In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:\\datasets\\tips.csv")

In [3]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [5]:
x = df.drop(columns = ['sex'], axis = 1)
y= df['sex']

In [6]:
print("Total data shape =", df.shape)
print("Independent data shape =", x.shape)
print("Dependent data shape =", y.shape)

Total data shape = (244, 7)
Independent data shape = (244, 6)
Dependent data shape = (244,)


In [7]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 4)

In [10]:
print("Total data shape =", df.shape)
print("Independent data shape =", x.shape)
print("Dependent data shape =", y.shape)
print("X_train data shape=", x_train.shape)
print("X_test data shape =", x_test.shape)
print("Y_train data shape =", y_train.shape)
print("Y_test data shape =", y_test.shape)

Total data shape = (244, 7)
Independent data shape = (244, 6)
Dependent data shape = (244,)
X_train data shape= (195, 6)
X_test data shape = (49, 6)
Y_train data shape = (195,)
Y_test data shape = (49,)


In [11]:
np.round(x_train.describe(), 1)


total_bill    tip   size
count       195.0  195.0  195.0
mean         20.0    3.1    2.6
std           9.0    1.4    0.9
min           3.1    1.0    1.0
25%          13.4    2.0    2.0
50%          17.8    3.0    2.0
75%          24.4    3.7    3.0
max          50.8   10.0    6.0

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc = StandardScaler()

In [17]:
x.head()

total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

## Column Transformer

In [2]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv("D:\\datasets\\covid_toy.csv")

In [4]:
df


age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop(
    columns = ['has_covid']), df['has_covid'], test_size = 0.2)

In [8]:
x_train

age  gender  fever   cough       city
56   71    Male    NaN  Strong    Kolkata
50   19    Male  101.0    Mild      Delhi
92   82  Female  102.0  Strong    Kolkata
44   20    Male  102.0  Strong      Delhi
88    5  Female  100.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
22   71  Female   98.0  Strong    Kolkata
79   48  Female  103.0    Mild    Kolkata
7    20  Female    NaN  Strong     Mumbai
66   51    Male  104.0    Mild    Kolkata
57   49  Female   99.0  Strong  Bangalore

[80 rows x 5 columns]

## Manually type output

In [9]:
#adding simple imputer to fever column
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])

# also the test data
x_test_fever = si.fit_transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [11]:
# Ordinal Encoding ===> Cough

oe = OrdinalEncoder(categories = [['Mild', 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [12]:
#oneHotEncoding ===> Gender, city

ohe = OneHotEncoder(drop ='first', sparse =False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender', 'city']])

x_train_gender_city.shape

F:\Python\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
F:\Python\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 4)

In [13]:
# Extracting Age

x_train_age = x_train.drop(columns =
                          ['gender', 'fever', 'cough', 'city']).values

# also the test data

x_test_age = x_test.drop(columns =
                        ['gender', 'fever', 'cough', 'city']).values

In [14]:
x_train_age.shape

(80, 1)

In [15]:
x_train_transformed = np.concatenate((x_train_age , x_train_fever,
                                     x_train_gender_city,
                                     x_train_cough), axis = 1)

In [16]:
# x_test_transformed = np.concatenate((x_test_age, x_test_fever, x_test_gender_city, x_test_cough))

In [17]:
x_train_transformed.shape

(80, 7)

### By the help of column Transformer

In [18]:
from sklearn.compose import ColumnTransformer # this is how to ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(),['fever']), # ina 'fever' column by the help of SI we fill missing values by mean, median, mode
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]),['cough']), # by this process we encode our data
    ('tnf3', OneHotEncoder(sparse=False,drop='first'),['gender','city'])
], remainder = 'passthrough') # reamaider==> it means rest all the columns remain same

In [20]:
transformer.fit_transform(x_train).shape

F:\Python\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 7)

In [22]:
transformer.transform(x_test).shape

(20, 7)

# What is Function Transformer in Machine Learning?

## The Function Trnasformer is a tool in scikit-learn, a popular Python library for machine learning, that allows you to apply a specified function to the input data. The function Transformer can be useful for performing custom transformationsof input data in a machine learning pipeline.

The FunctionTrnasformer takes as input a single function that will be applied to each sample in the data. This function can be any Python function takes a single argument, such as a lambda function or a user-function. The function should return the transformed sample.

In [24]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset
X= np.array([[1,2],[3,4]]) 

#define the tranformation function
log_transform = FunctionTransformer(np.log1p)

#apply the transformation to the dataset
X_transformed = log_transform.transform(X)

# view the transformed data
print(X_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [26]:
#Practical usecasses

#1. Custom Feature Engineering

from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset
X = np.array ([[1,2],[3,4]])

def my_feature_engineering(X):
    return np.hstack((X, X**2))

# create a FunctionTransformer to apply the custom function 
custom_transformer = FunctionTransformer(my_feature_engineering)

function#apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [28]:
#2. Scaling and Normalization

# create a dataset
X= np.array([[1,2], [3,4]])

# define a custom scaling function
def my_scaling(X):
    return X/np.max(X)

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(my_scaling)

#apply the transformer to the input data
X_tranformed = custom_transformer.transform(X)

#view the transformed data
print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [29]:
# 3. Data Cleaning

# create a dataset with missing values
X= np.array([[1,2],[3,np.nan]])

# define a custom cleaning function
def my_cleaning(X):
    X[np.isnan(X)] = 0
    return X

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(my_cleaning)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

[[1. 2.]
 [3. 0.]]
