In [1]:
import numpy as np

In [3]:
a = [1,2,3,4]
b = np.array(a)
b

array([1, 2, 3, 4])

In [4]:
a = []
size = int(input("enter size :"))
for i in range(size):
    val = int(input("enter number :"))
    a.append(val)

print(a)
b = np.array(a)
b

enter size : 3
enter number : 1
enter number : 2
enter number : 3


[1, 2, 3]


array([1, 2, 3])

In [5]:
a = [[1,2,3] , [4,5,6] , [7,8,9]]
b =np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print("Total Dimensions :" , b.ndim) #* 
print("Shape of an array :" , b.shape) #shape = n(rows), n(columns)

Total Dimensions : 2
Shape of an array : (3, 3)


In [9]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [11]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [13]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [17]:
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [19]:
a = np.random.randint(1,10,3)
a

array([8, 9, 8])

In [20]:
a = np.random.rand(5)
a

array([0.41558796, 0.40680954, 0.67436547, 0.59143409, 0.55401208])

In [21]:
a = np.random.randn(5)
a

array([-0.1075435 ,  1.86212199, -0.59930902, -0.82087696,  1.50746934])

In [22]:
a = np.random.randint(1,50,12)
a

array([24, 42, 27,  2, 38,  2,  2,  5, 40,  9, 22, 41])

In [23]:
a.shape

(12,)

In [24]:
a = a.reshape(2,6)
a

array([[24, 42, 27,  2, 38,  2],
       [ 2,  5, 40,  9, 22, 41]])

In [25]:
a = a.reshape(6,2)
a

array([[24, 42],
       [27,  2],
       [38,  2],
       [ 2,  5],
       [40,  9],
       [22, 41]])

In [26]:
a = a.reshape(3,4)
a

array([[24, 42, 27,  2],
       [38,  2,  2,  5],
       [40,  9, 22, 41]])

In [27]:
a = a.reshape(4,3)
a

array([[24, 42, 27],
       [ 2, 38,  2],
       [ 2,  5, 40],
       [ 9, 22, 41]])

In [28]:
a = a.reshape(12,1)
a

array([[24],
       [42],
       [27],
       [ 2],
       [38],
       [ 2],
       [ 2],
       [ 5],
       [40],
       [ 9],
       [22],
       [41]])

In [29]:
a = a.reshape(-1,4)
a

array([[24, 42, 27,  2],
       [38,  2,  2,  5],
       [40,  9, 22, 41]])

In [31]:
np.random.seed(5)
a = np.random.randint(1,100,10)
a

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [33]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6]
b[:] = 0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [34]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [35]:
b

array([0, 0, 0])

In [36]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [40]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [41]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [42]:
a = np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [43]:
a+2

array([3, 4, 5, 6])

In [44]:
a**2

array([ 1,  4,  9, 16])

In [54]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [55]:
b = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [56]:
a+b

array([[ 6,  8],
       [10, 12]])

In [57]:
b-a

array([[4, 4],
       [4, 4]])

In [58]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [59]:
a*b

array([[ 5, 12],
       [21, 32]])

In [60]:
a.dot(b) #*

array([[19, 22],
       [43, 50]])

In [61]:
a = np.array([10,20,30,40,50])
np.min(a)

10

In [63]:
np.max(a)

50

In [64]:
np.argmin(a)

0

In [65]:
np.argmax(a)

4

In [66]:
np.sqrt(a) 

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [67]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [68]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [69]:
np.random.seed(122) 
a = np.random.randint(1,21,9).reshape(3,3) 
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [70]:
np.sum(a)

116

In [71]:
np.sum(a , axis = 1)

array([40, 46, 30])

In [72]:
np.min(a)

3

In [73]:
np.max(a)

17

In [74]:
np.cumsum(a)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])

In [75]:
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [77]:
a = np.array([10,20,30,40,10,20,50])
np.unique(a , return_index = True , return_counts = True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

In [78]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [79]:
b

array([5, 6, 7, 8])

In [80]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])